### ISSUE TITLE
cli throws error 

### ISSUE THREAD

**Issue by tbrooke** [commonform/commonform-cli#20]
On OSX running version 0.12.1I get the following error:
commonform render < welcome-form.cform

/usr/local/lib/node_modules/commonform-cli/node_modules/commonform-markup-parse/parser.js:151
        throw new _parseError(str, hash);
        ^
Error
    at Object.parseError (/usr/local/lib/node_modules/commonform-cli/node_modules/commonform-markup-parse/parser.js:149:33)
    at Object.parse (/usr/local/lib/node_modules/commonform-cli/node_modules/commonform-markup-parse/parser.js:216:22)
    at module.exports (/usr/local/lib/node_modules/commonform-cli/node_modules/commonform-markup-parse/index.js:9:23)
    at transform (/usr/local/lib/node_modules/commonform-cli/source/read-input.js:10:52)
    at /usr/local/lib/node_modules/commonform-cli/source/read-input.js:11:20
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/commonform-cli/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/local/lib/node_modules/commonform-cli/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at endWritable (/usr/local/lib/node_modules/commonform-cli/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:521:3)

**Comment by kemitchell** [comment]
Thanks, Tom! I'll have a look.

**Comment by kemitchell** [comment]
Can you share welcome-form.cform? If not here, I'll be happy to receive by e-mail and glance privately.

**Comment by tbrooke** [comment]
I somehow tweaked the form and had:

`/Welcome./ This is a . . .`

Instead of:

```
/Welcome./ This is a . . .`  
```

I had the \Welcome at the start of the line and it threw a non descriptive error - When the indent was off by one or two it would do an "Invalid indention on line" error which was better but I see the problem so it is fine

**Comment by kemitchell** [comment]
No problem.

Just a quick note: You can probably leave the terminal periods out of your headings:

``` commonform
\Welcome\ This is a ...
```

Formatting commands like `commonform render -f docx` will add appropriate punctuation for you.

**Comment by tbrooke** [comment]
That was just because I wasn't showing more text

**Comment by kemitchell** [comment]
Sorry. I meant the period after "Welcome".
